services:
  django-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django-docker
    command:
      - /bin/sh
      - '-c'
      - '/app/start.sh'
    ports:
      - "8000:8000"
  analysis-worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django-analysis-worker
    profiles:
      - worker
    command:
      - /bin/sh
      - '-c'
      - '/app/start-worker.sh'
