# Generated by Django 4.2.23 on 2025-08-27 05:50

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadedImage",
            fields=[
                ("name", models.TextField()),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "file_location",
                    models.FileField(upload_to=core.models.UploadedImage.upload_to),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SegmentedImage",
            fields=[
                ("UUID", models.UUIDField(primary_key=True, serialize=False)),
                ("uploaded_date", models.DateTimeField(auto_now_add=True)),
                (
                    "file_location",
                    models.FileField(upload_to=core.models.user_directory_path),
                ),
                ("ImagePath", models.FilePathField()),
                ("CellPairPrefix", models.FilePathField()),
                ("NumCells", models.IntegerField()),
                (
                    "user",
                    models.ForeignKey(
                        default=core.models.get_guest_user,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DVLayerTifPreview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wavelength", models.CharField(max_length=30)),
                ("file_location", models.ImageField(upload_to="")),
                (
                    "uploaded_image_uuid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.uploadedimage",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CellStatistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cell_id", models.IntegerField()),
                ("distance", models.FloatField()),
                ("line_gfp_intensity", models.FloatField()),
                ("nucleus_intensity_sum", models.FloatField()),
                ("cellular_intensity_sum", models.FloatField()),
                ("cytoplasmic_intensity", models.FloatField(default=0.0)),
                ("blue_contour_size", models.FloatField(default=0.0)),
                ("red_contour_1_size", models.FloatField(default=0.0)),
                ("red_contour_2_size", models.FloatField(default=0.0)),
                ("red_contour_3_size", models.FloatField(default=0.0)),
                ("red_intensity_1", models.FloatField(default=0.0)),
                ("red_intensity_2", models.FloatField(default=0.0)),
                ("red_intensity_3", models.FloatField(default=0.0)),
                ("green_intensity_1", models.FloatField(default=0.0)),
                ("green_intensity_2", models.FloatField(default=0.0)),
                ("green_intensity_3", models.FloatField(default=0.0)),
                ("green_red_intensity_1", models.FloatField(default=0.0)),
                ("green_red_intensity_2", models.FloatField(default=0.0)),
                ("green_red_intensity_3", models.FloatField(default=0.0)),
                ("red_blue_intensity_1", models.FloatField(default=0.0)),
                ("red_blue_intensity_2", models.FloatField(default=0.0)),
                ("red_blue_intensity_3", models.FloatField(default=0.0)),
                ("cellular_intensity_sum_DAPI", models.FloatField(default=0.0)),
                ("nucleus_intensity_sum_DAPI", models.FloatField(default=0.0)),
                ("cytoplasmic_intensity_DAPI", models.FloatField(default=0.0)),
                ("dv_file_path", models.TextField(default="")),
                ("image_name", models.TextField(default="")),
                ("is_correct", models.BooleanField(default=True)),
                ("nuclei_count", models.IntegerField(default=1)),
                ("gfp_dot_count", models.IntegerField(default=0)),
                ("red_dot_distance", models.FloatField(default=0.0)),
                ("gfp_red_dot_distance", models.FloatField(default=0.0)),
                ("cyan_dot_count", models.IntegerField(default=1)),
                ("ground_truth", models.BooleanField(default=False)),
                ("nucleus_intensity", models.JSONField(default=dict)),
                ("nucleus_total_points", models.IntegerField(default=0)),
                ("cell_intensity", models.JSONField(default=dict)),
                ("cell_total_points", models.IntegerField(default=0)),
                ("ignored", models.BooleanField(default=False)),
                ("mcherry_line_gfp_intensity", models.FloatField(default=0.0)),
                ("gfp_line_gfp_intensity", models.FloatField(default=0.0)),
                ("properties", models.JSONField(default=dict)),
                (
                    "segmented_image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.segmentedimage",
                    ),
                ),
            ],
        ),
    ]
