# Generated by Django 4.2.23 on 2026-01-29 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cellstatistics",
            name="biorientation",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="cellstatistics",
            name="category_GFP_dot",
            field=models.IntegerField(
                choices=[
                    (1, "One green dot with each red dot"),
                    (2, "One green dot with one red dot"),
                    (3, "Two green dots with one red dot"),
                    (4, "N/A"),
                ],
                default=4,
            ),
        ),
    ]
