# Generated by Django 5.0.6 on 2026-03-01 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_uploadedimage_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="cellstatistics",
            name="gfp_contour_1_size",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="cellstatistics",
            name="gfp_contour_2_size",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="cellstatistics",
            name="gfp_contour_3_size",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="cellstatistics",
            name="gfp_to_mcherry_distance_1",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="cellstatistics",
            name="gfp_to_mcherry_distance_2",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="cellstatistics",
            name="gfp_to_mcherry_distance_3",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="cellstatistics",
            name="green_in_green_intensity_1",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="cellstatistics",
            name="green_in_green_intensity_2",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="cellstatistics",
            name="green_in_green_intensity_3",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="cellstatistics",
            name="red_in_green_intensity_1",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="cellstatistics",
            name="red_in_green_intensity_2",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="cellstatistics",
            name="red_in_green_intensity_3",
            field=models.FloatField(default=0.0),
        ),
    ]
