# Generated by Django 5.2.11 on 2026-03-03 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_cellstatistics_extended_intensity_metrics"),
    ]

    operations = [
        migrations.AddField(
            model_name="cellstatistics",
            name="gfp_drift_any",
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="cellstatistics",
            name="gfp_drift_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="cellstatistics",
            name="gfp_drift_flag_1",
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="cellstatistics",
            name="gfp_drift_flag_2",
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="cellstatistics",
            name="gfp_drift_flag_3",
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="cellstatistics",
            name="gfp_drift_unknown_reason",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
