# Generated by Django 5.2.11 on 2026-03-03 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_cellstatistics_gfp_drift_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cellstatistics",
            name="gfp_drift_any",
        ),
        migrations.RemoveField(
            model_name="cellstatistics",
            name="gfp_drift_count",
        ),
        migrations.RemoveField(
            model_name="cellstatistics",
            name="gfp_drift_flag_1",
        ),
        migrations.RemoveField(
            model_name="cellstatistics",
            name="gfp_drift_flag_2",
        ),
        migrations.RemoveField(
            model_name="cellstatistics",
            name="gfp_drift_flag_3",
        ),
        migrations.RemoveField(
            model_name="cellstatistics",
            name="gfp_drift_unknown_reason",
        ),
    ]
