# Generated by Django 5.2.11 on 2026-03-10 03:25

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_cellstatistics_gfp_drift_any_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimage',
            name='scale_info',
            field=models.JSONField(default=core.models.default_scale_info),
        ),
    ]
