# Generated by Django 5.2.11 on 2026-04-25 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_align_upload_preparation_job_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadpreparationjob',
            name='progress_detail',
            field=models.JSONField(default=dict),
        ),
    ]