# Generated by Django 5.2.11 on 2026-06-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_add_job_progress_detail"),
    ]

    operations = [
        migrations.AddField(
            model_name="cellstatistics",
            name="nuclear_cytoplasmic_ratio",
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
