# Generated by Django 5.2.11 on 2026-06-09 23:14

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_cellstatistics_nuclear_cytoplasmic_ratio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dvlayertifpreview",
            name="file_location",
            field=models.ImageField(max_length=512, upload_to=""),
        ),
        migrations.AlterField(
            model_name="segmentedimage",
            name="CellPairPrefix",
            field=models.FilePathField(max_length=512),
        ),
        migrations.AlterField(
            model_name="segmentedimage",
            name="ImagePath",
            field=models.FilePathField(max_length=512),
        ),
        migrations.AlterField(
            model_name="segmentedimage",
            name="file_location",
            field=models.FileField(
                max_length=512, upload_to=core.models.user_directory_path
            ),
        ),
        migrations.AlterField(
            model_name="uploadedimage",
            name="file_location",
            field=models.FileField(
                max_length=512, upload_to=core.models.UploadedImage.upload_to
            ),
        ),
    ]
