# Generated by Django 5.0.4 on 2024-05-21 08:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_rename_original_name_uploadedimage_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedimage",
            name="file_location",
            field=models.FileField(default="dummyvalue", upload_to="test"),
            preserve_default=False,
        ),
    ]
