# Generated by Django 4.2.23 on 2026-01-29 05:37

import core.config
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="config",
            field=models.JSONField(default=core.config.default_process_config),
        ),
    ]
