# Generated by Django 5.0.6 on 2026-02-03 03:39

from django.contrib.auth.hashers import make_password
from django.db import migrations


def create_guest_user(apps, schema_editor):
    CustomUser = apps.get_model("accounts", "CustomUser")
    guest_email = "guest@local.invalid"
    guest, created = CustomUser.objects.get_or_create(
        email=guest_email,
        defaults={
            "is_active": False,
            "is_staff": False,
            "is_superuser": False,
            "first_name": "Guest",
            "last_name": "User",
            "password": make_password(None),
        },
    )
    if created:
        guest.save(update_fields=["password"])


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0003_alter_customuser_options_alter_customuser_managers_and_more",
        ),
    ]

    operations = [
        migrations.RunPython(create_guest_user, migrations.RunPython.noop),
    ]
