# Generated by Django 5.0.6 on 2026-03-31 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_create_guest_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="available_storage",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="total_storage",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="used_storage",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="customuser",
            name="quota_override_bytes",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="quota_override_mode",
            field=models.CharField(
                choices=[
                    ("default", "Use policy default"),
                    ("bonus", "Add bonus"),
                    ("fixed", "Use fixed quota"),
                ],
                default="default",
                max_length=16,
            ),
        ),
    ]
